name: Docker CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout repo
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Docker
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Build Docker image
    - name: Build Docker image
      run: docker build -t docker-python-app .

    # Optional: Run container to verify it starts
    - name: Run Docker container
      run: |
        docker run -d -p 8080:8080 docker-python-app
        docker ps
